### ISSUE TITLE
Docker file Error: environment variable "JAVA_HOME" must be set to a JDK (>= v1.7)

### ISSUE THREAD

**Issue by marujore** [schwankner/esa-snap-with-python#1]
When running the dockerfile I get Error: environment variable "JAVA_HOME" must be set to a JDK (>= v1.7) installation directory:

Step 1/8 : FROM mrmoor/esa-snap:latest
 ---> c5215ce98585
Step 2/8 : RUN apt-get update &&     apt-get -y install default-jdk python3 python3-pip git maven
 ---> Using cache
 ---> 938ab2f88a00
Step 3/8 : RUN python3 -m pip install --user --upgrade setuptools wheel
 ---> Using cache
 ---> 90f8faf88796
Step 4/8 : RUN export JDK_HOME="/usr/lib/jvm/default-java"
 ---> Using cache
 ---> 9c0ef0103766
Step 5/8 : RUN cd /tmp/ &&     git clone https://github.com/bcdev/jpy.git &&     cd /tmp/jpy/ &&     python3 setup.py --maven bdist_wheel &&     mkdir -p /root/.snap/snap-python/snappy/&&     cp /tmp/jpy/dist/* /root/.snap/snap-python/snappy/
 ---> Running in 0e0d470d8d60
Cloning into 'jpy'...
Error: environment variable "JAVA_HOME" must be set to a JDK (>= v1.7) installation directory
The command '/bin/sh -c cd /tmp/ &&     git clone https://github.com/bcdev/jpy.git &&     cd /tmp/jpy/ &&     python3 setup.py --maven bdist_wheel &&     mkdir -p /root/.snap/snap-python/snappy/&&     cp /tmp/jpy/dist/* /root/.snap/snap-python/snappy/' returned a non-zero code: 1

**Comment by schwankner** [comment]
I fixed this Issue by updating the code to work with Snap 7 but it sadly only works with python 2.7

**Comment by whatnick** [comment]
Would there be interest in making this work in Python3.6 since this is 2020 and Python2.7 is deprecated. Opening #3.
