### ISSUE TITLE
Initializing python

### ISSUE THREAD

**Issue by luisaintonio** [schwankner/esa-snap-with-python#2]
Is there a way to initialize the python shell? to test some commands?
how do i compile my python scripts? there's no help online, this is my last resort...

**Comment by schwankner** [comment]
Yes, you can start the container with `docker run -it --entrypoint /bin/bash mrmoor/esa-snap-with-python` to get a bash or `docker run -it --entrypoint python mrmoor/esa-snap-with-python` to start the interactive python shell.
On the bash you can run the gtp command to process your own snap graph xml files. On how to use the python snap module have a look on the CPython approach at https://senbox.atlassian.net/wiki/spaces/SNAP/pages/19300362/How+to+use+the+SNAP+API+from+Python
